<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends EntityRepository
{
    public function findMovies($number){
        $qb=$this->createQueryBuilder("a");

        $query=$qb
            ->setMaxResults($number)
            ->getQuery();

        return $query->getResult();
    }
    public function findMoreMovies($start,$qty){
        $qb=$this->createQueryBuilder("a");

        $query=$qb
            ->setFirstResult($start)
            ->setMaxResults($qty)
            ->getQuery();

        return $query->getResult();
    }
}
